FirstProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

import MyProfile.urls as MyProfile
from MyProfile import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage),
    url(r'^MyProfile/', include(MyProfile, namespace="MyProfile"))
]

MyProfile/urls.py
from django.conf.urls import url
from . import views
app_name = "MyProfile"
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^portofolio/$', views.portofolio, name="portofolio"),
    url(r'^guestbook/$', views.guestbook, name="guestbook"),
    url(r'^eventform/$', views.eventFormPost, name="eventform"),
    url(r'^eventlist/$', views.eventList, name="eventlist"),
    url(r'^eventlist-delete/$', views.eventListDelete, name="eventlistdelete"),
]

MyProfile/models.py
from django.db import models
    
class EventModel(models.Model):
    date = models.DateTimeField()
    event = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
        
    def __str__(self):
        return self.event

MyProfile/forms.py
from django import forms
from .models import EventModel

class EventForm(forms.ModelForm):
    date = forms.DateTimeField(widget=forms.DateTimeInput(
        attrs={
            'class':'form-control',
            'placeholder':'YYYY-MM-DD hh:mm',
            'type':'datetime-local'
            
        }
    ),input_formats=['%Y-%m-%dT%H:%M'])
    event = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'What is the event...'
        }
    ))
    place = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'Where it will be...'
        }
    ))
    category = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'What is the catagory...'
        }
    ))

    class Meta:
        model = EventModel
        fields = ('date', 'event', 'place', 'category')

MyProfile/views.py
from django.shortcuts import render,redirect
from .forms import EventForm
from .models import EventModel

def homepage(request):
    return render(request, "Homepage.html", {})

def portofolio(request):
    return render(request, "Portofolio.html", {})

def guestbook(request):
    return render(request, "Guest-book.html", {})

def eventFormPost(request):
    if request.method ==  "POST":
        form = EventForm(request.POST)
        if(form.is_valid()):
            form_item = form.save(commit=False)
            form_item.save()
            form = EventForm()
            return redirect('/MyProfile/eventform/')
    else:
        form = EventForm()
    return render(request, "eventform.html", {'form': form})

def eventList(request):
    allEvent = EventModel.objects.all().order_by('date')
    return render(request, "eventlist.html", {'allEvent': allEvent})

def eventListDelete(request):
    allEvent = EventModel.objects.all().delete()
    return redirect('/MyProfile/eventlist/')

MyProfile/templates/Guest-book.html
{% extends "base.html" %}

{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Guest Book</title>
{% endblock%}

{% block body %}

<div class="content-d">
    <div class="title">
        <h1>
            GUEST BOOK
        </h1>
    </div>
    <div class="input-form">
        <form>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="input-label">Name:</label>
                <input type="text" class="form-control" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="input-label">Date:</label>
                <input type="date" class="form-control">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="input-label">Email address:</label>
                <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="input-label">Subject:</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Subject">
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1" class="input-label">Message:</label>
                <textarea class="form-control" id="textarea" rows="3" placeholder="Message"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

MyProfile/templates/Homepage.html
{% extends "base.html" %}
{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Mohammad Wildan Yanuar</title>
{% endblock %}

{% block body %}

<div class="header">
    <div class="background"></div>
    <div class="img-me">
        <img src="https://www.imageupload.co.uk/images/2018/09/27/foto.png" alt="">
    </div>
    <div class="name">
        <h1>i'm yayan</h1>
        <h3>information system student<br>University of Indonesia</h3>
    </div>
    <div class="introduction">
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique neque fugiat temporibus, sit
            reiciendis, nostrum, rem iusto officiis ad soluta doloremque assumenda in architecto. Pariatur.</p>
    </div>
    <a class="btn" href="#">contact</a>
</div>
<div class="content-a">
    <div class="title">
        <h1>1. skill</h1>
    </div>
    <div class="skill">
        <ul>
            <li>
                <h3>HTML</h3>
                <span class="bar">
                    <span class="html">
                    </span>
                </span>
            </li>
            <li>
                <h3>CSS</h3>
                <span class="bar">
                    <span class="css">
                    </span>
                </span>
            </li>
            <li>
                <h3>python</h3>
                <span class="bar">
                    <span class="python">
                    </span>
                </span>
            </li>
        </ul>
    </div>
</div>
<div class="content-b">
    <div class="title">
        <h1>2. PORTOFOLIO</h2>
    </div>
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big1.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big2.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big3b6bba.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big4.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big5.jpg" alt="">
</div>
<div class="content-c">
    <div class="title">
        <h1>3. contact</h1>
    </div>
    <div class="contact">
        <ul>
            <li>
                <img src="https://www.imageupload.co.uk/images/2018/09/27/Phone.png" alt="">
                <p>081286227658</p>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/mohammadwildanyanuar/" class="contact-b" id="contact2b" style="text-decoration:none">
                    <img src="https://www.imageupload.co.uk/images/2018/09/27/linkin.png" alt="">
                    <br>
                    Mohammad Wildan Yanuar
                </a>
            </li>
            <li>
                <a href="https://www.facebook.com/mohammadwildan.yanuar" class="contact-b" id="contact3b" style="text-decoration:none">
                    <img src="https://www.imageupload.co.uk/images/2018/09/27/facebook.png" alt="">
                    <br>
                    Mohammad Wildan Yanuar
                </a>
            </li>
            <li>
                <a href="https://www.instagram.com/mohammadwildany/" class="contact-b" id="contact4b" style="text-decoration:none">
                    <img src="https://www.imageupload.co.uk/images/2018/09/27/instagram.png" alt="">
                    <br>
                    mohammadwildany
                </a>
            </li>
        </ul>
    </div>
</div>

{% endblock %}

MyProfile/templates/Portofolio.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">

{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Portofolio</title>
{% endblock %}

{% block body %}
<div class="content-b">
    <div class="title">
        <h1>2. PORTOFOLIO</h2>
    </div>
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big1.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big2.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big3b6bba.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big4.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big5.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big6.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big7.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big8.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big9.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big10.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big11.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big12.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big13.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big14.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big16.jpg" alt="">
</div>

{% endblock %}

MyProfile/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <link href="{% static 'style-coba.css'%}"rel="stylesheet">
    {% block head %}
    {% endblock%}
</head>

<body>
    <div class="wrapper">
        <div class="menu">
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'MyProfile:homepage' %}">
                            <img src="https://www.imageupload.co.uk/images/2018/09/27/Design.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">About Me</a>
                    </li>
                    <li>
                        <a href="{% url 'MyProfile:portofolio' %}">Portofolio</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    <li>
                        <a href="{% url 'MyProfile:guestbook' %}">Guest Book</a>
                    </li>
                    <li>
                        <a href="{% url 'MyProfile:eventform' %}">Event Form</a>
                    </li>
                    <li>
                        <a href="{% url 'MyProfile:eventlist' %}">Event List</a>
                    </li>
                </ul>
            </nav>
        </div>
        {% block body %}
        {% endblock %}
        <div class="footer" id="bawah">
            <p>Created by Mohammad Wildan Yanuar</p>
        </div>
    </div>
</body>

</html>

MyProfile/templates/eventform.html
{% extends "base.html" %}

{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Event Form</title>
{% endblock%}

{% block body %}

<div class="content-d">
    <div class="title">
        <h1>
            EVENT FORM
        </h1>
    </div>
    <div class="input-form">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

MyProfile/templates/eventlist.html
{% extends "base.html" %}

{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Event Form</title>
{% endblock%}

{% block body %}

<div class="content-d">
    <div class="title">
        <h1>
            EVENT LIST
        </h1>
    </div>
    <div class="input-form">
        {% for event in allEvent %}
            <h2>{{ event.event }}</h2>
            <p>{{ event.category }}</p>
            <p>{{ event.place }}, {{ event.date }}</p>
        {% endfor %}
        <a class="button-delete" href="{% url 'MyProfile:eventlistdelete' %}">Delete All</a>
    </div>
</div>

{% endblock %}